/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#77ffbb",
        "primary-hover": "#4dffb1",
        "accent-lime": "#05e699",
        "background-light": "#fafaf9",
        "background-dark": "#1c1f22",
        "card-dark": "#2B3036",
        "card-light": "#ffffff",
        "text-secondary-dark": "#849589",
        "text-secondary-light": "#849589",
        "surface-dark": "#1a1c20",
        "surface-border": "#282a2e",
        
        // New Palette from code.html
        "on-surface-variant": "#bacbbe",
        "surface-variant": "#333539",
        "on-tertiary-fixed-variant": "#930014",
        "tertiary-container": "#ffb8b3",
        "tertiary": "#ffdedc",
        "on-tertiary-container": "#ac061b",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-tertiary": "#68000b",
        "inverse-primary": "#006c46",
        "surface-bright": "#37393e",
        "primary-fixed": "#4dffb1",
        "on-primary-fixed-variant": "#005233",
        "secondary": "#92d5ae",
        "on-surface": "#e2e2e8",
        "on-primary-fixed": "#002112",
        "on-primary": "#003822",
        "on-secondary-fixed": "#002112",
        "inverse-on-surface": "#2f3035",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0c0e12",
        "on-secondary-container": "#84c6a0",
        "on-secondary-fixed-variant": "#065134",
        "surface-container": "#1e2024",
        "secondary-container": "#0b5436",
        "outline": "#849589",
        "surface-container-high": "#282a2e",
        "surface-dim": "#111317",
        "error": "#ffb4ab",
        "surface": "#111317",
        "surface-tint": "#00e296",
        "on-error": "#690005",
        "background": "#111317",
        "outline-variant": "#3b4a40",
        "secondary-fixed-dim": "#92d5ae",
        "on-primary-container": "#00623e",
        "surface-container-low": "#1a1c20",
        "secondary-fixed": "#adf1c9",
        "primary-fixed-dim": "#00e296",
        "tertiary-fixed": "#ffdad7",
        "surface-container-highest": "#333539",
        "inverse-surface": "#e2e2e8",
        "on-tertiary-fixed": "#410004",
        "on-secondary": "#003822",
        "primary-container": "#05e699",
        "error-container": "#93000a",
        "on-background": "#e2e2e8",
        "cero-danger": "#FF4D4D"
      },
      boxShadow: {
        'soft': '0 4px 20px -2px rgba(0, 0, 0, 0.1)',
        'glow': '0 0 15px rgba(31, 107, 122, 0.3)',
      },
      fontFamily: {
        "display": ["Manrope", "sans-serif"],
        "heading": ["Space Grotesk", "sans-serif"],
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "0.75rem"
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      }
    },
  },
  plugins: [],
}
