using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Fintrack.Server.Migrations
{
    /// <inheritdoc />
    public partial class BudgetPrimaryKeyGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // PostgreSQL cannot cast integer PK to uuid. Budget rows are cleared; CategoryId (int) is unchanged.
            migrationBuilder.Sql(
                """
                DELETE FROM "Budgets";
                ALTER TABLE "Budgets" DROP CONSTRAINT "PK_Budgets";
                ALTER TABLE "Budgets" DROP COLUMN "Id";
                ALTER TABLE "Budgets" ADD COLUMN "Id" uuid NOT NULL;
                ALTER TABLE "Budgets" ADD CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM "Budgets";
                ALTER TABLE "Budgets" DROP CONSTRAINT "PK_Budgets";
                ALTER TABLE "Budgets" DROP COLUMN "Id";
                ALTER TABLE "Budgets" ADD COLUMN "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;
                ALTER TABLE "Budgets" ADD CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id");
                """);
        }
    }
}
